version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  php:
    image: php:fpm-alpine
    volumes:
      - ./app:/app
    restart: always
networks:
  default:
    external:
      name: web
